// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/metricas/Compacto.tsx": () => import("../components/mockups/metricas/Compacto.tsx"),
  "./components/mockups/metricas/Completo.tsx": () => import("../components/mockups/metricas/Completo.tsx")
};
